name: Github CI build

on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
    
      - master
env:
  RELEASE4: 4.6.0.13
  RELEASE5: 5.0.0.43

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare sfos 4 build
      run: rm -rf RPMS
      
    - name: Build armv7hl
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE4 }}
        arch: armv7hl

    - name: Build aarch64
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE4 }}
        arch: aarch64

    - name: Build i486
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE4 }}
        arch: i486
      
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: output-rpms
        path: RPMS

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        gh release create "$tag_name" "${assets[@]}" --title "$tag_name $RELEASE4"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare sfos 5 build
      run: rm -rf RPMS
      
    - name: Build armv7hl
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE5 }}
        arch: armv7hl

    - name: Build aarch64
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE5 }}
        arch: aarch64

    - name: Build i486
      uses: coderus/github-sfos-build@master
      with:
        release: ${{ env.RELEASE5 }}
        arch: i486
      
    - name: Upload build result
      uses: actions/upload-artifact@v4
      with:
        name: output-rpms
        path: RPMS

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        gh release create "$tag_name" "${assets[@]}" --title "$tag_name $RELEASE5"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}